apiVersion: batch/v1
kind: Job
metadata:
  name: jmx
spec:
  ttlSecondsAfterFinished: 10
  # activeDeadlineSeconds: 180
  template:
    spec:
      initContainers:
        - name: boxter
          image: mx2542/boxter:1.0
          command:
            - "./boxter.sh"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /cache-jmx
              name: cache-jmx
          env:
            - name: URL
              value: "http://middleware-minio.tink:9000"
            - name: USER
              value: admin
            - name: PASSWORD
              value: changeme
            - name: BUCKET_NAME
              value: jmx
            - name: TASK_NAME
              value: example
      containers:
        - name: jmeter
          image: mx2542/anti-jmeter:1.0
          command:
            - "bash"
          args:
            - "-c"
            - "./apache-jmeter-5.4.3/bin/jmeter.sh -n -t /cache-jmx/example.jmx > /cache/jmeter.jtl && rm -f /cache/jmeter.jtl"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /cache-jmx
              name: cache-jmx

        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.17.3
          imagePullPolicy: IfNotPresent
          args:
            - "-e"
            - "-E"
            - "http.enabled=true"
          livenessProbe:
            exec:
              command:
                - cat
                - /cache/jmeter.jtl
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: filebeat-config-demo
              readOnly: true
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - mountPath: /cache
              name: cache-volume
          env:
            - name: TASK_TYPE
              value: test
            - name: TASK_NAME
              value: "3"
      restartPolicy: Never
      volumes:
        - name: filebeat-config-demo
          configMap:
            name: filebeat-config-demo
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: cache-jmx
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
  backoffLimit: 3
