---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-demo

data:
  filebeat.yml: |
    filebeat.inputs:
    - type: filestream
      paths:
        - /cache/*.jtl
        - /cache/*.log

    # output.console:
    #   pretty: true

    output.kafka:
      hosts: ["middleware-kafka.tink:9092"]
      topic: '${JOB_TOPIC}'
      # topic: '%{[agent.name]}'
      partition.round_robin:
        reachable_only: false

      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

---
apiVersion: batch/v1
kind: Job
metadata:
  name: jmx

spec:
  ttlSecondsAfterFinished: 10
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:2.8.1-debian-10-r31
          command: 
            - "bash"
            - "-c"
          args:
            # - "kafka-consumer-perf-test.sh --topic jmx --broker-list middleware-kafka.tink:9092 --messages 1000 > /cache/kafka.log"
            - "kafka-producer-perf-test.sh --topic kafka-test --throughput -1 --num-records 30000000000 --record-size 1024 --producer-props acks=all bootstrap.servers=middleware-kafka.tink:9092 > /cache/kafka.log && rm /cache/kafka.log"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /cache
              name: cache-volume

        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.17.3          
          imagePullPolicy: IfNotPresent
          args:
            - "-e"
            - "-E"
            - "http.enabled=true"
          livenessProbe:
            exec:
              command:
              - cat
              - /cache/kafka.log
          volumeMounts:
            - name: filebeat-config-demo
              readOnly: true
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - mountPath: /cache
              name: cache-volume
          env:
            - name: JOB_TOPIC
              value: jmx

      restartPolicy: Never
      volumes:
        - name: filebeat-config-demo
          configMap:
            name: filebeat-config-demo
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: cache-volume
          emptyDir: {}
  backoffLimit: 4